### ISSUE TITLE
"fn deploy" deletes comments from the func file

### ISSUE THREAD

**Issue by denismakogon** [fnproject/cli#244]
# Problem
`fn deploy` deletes comments from the func file.

## Steps to reproduce
Assume that you have comments in func file:
```yaml
name: func
version: 0.0.1
runtime: go
type: async
memory: 64
format: json
timeout: 10
path: /submit
config:
## this is A
  A: "A"
## this is B
  B: "B"
```
then call the deploy:
```bash
$ fn -v deploy --registry `whoami`
```
## Problem area
Comments will go away. This happens because CLI basically rewrites the func file.

# Use cases
There are few valid use cases that i can foresee like:
 - "comment temporarily the config var, call the deploy"
 - "in comments i want to put the env vars description"

maybe something else there?
