### ISSUE TITLE
`fn init` should reject invalid values for `--trigger`

### ISSUE THREAD

**Issue by rikgibson** [fnproject/cli#421]
The only valid value for `--trigger` at the moment is `http` but right now any value is accepted and a generic trigger block generated in `func.yaml`, e.g.

```
[~/test]: fn init --runtime java --trigger blah v2-trig-blah
Creating function at: /v2-trig-blah
Function boilerplate generated.
func.yaml created.

[~/test]: cat v2-trig-blah/func.yaml
schema_version: 20180708
name: v2-trig-blah
version: 0.0.1
runtime: java
build_image: fnproject/fn-java-fdk-build:jdk9-1.0.64
run_image: fnproject/fn-java-fdk:jdk9-1.0.64
cmd: com.example.fn.HelloFunction::handleRequest
format: http
triggers:
- name: v2-trig-blah-trigger
  type: blah
  source: /v2-trig-blah-trigger
```

Correct behaviour should be an error message something along the lines of "`blah` is not a valid trigger type."
