### ISSUE TITLE
fn update context failed where context has nested values

### ISSUE THREAD

**Issue by riconnon** [fnproject/cli#437]
Using a context with hierarchical values (eg. one using the Oracle provider) `fn update context` will return:
```
Fn: yaml: unmarshal errors:
  line 5: cannot unmarshal !!map into string
```

Sample context config:
```
api-url: https://api.fn.example.com
call-url: https://call.fn.example.com
provider: oracle
oracle:
  profile: oci-profile-name
  compartment-id: ocid1.compartment.oc1..abcdefghijklmnopqrstuvwxyz
```
